# Generated by Django 3.0.5 on 2020-05-02 16:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dictclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=255)),
                ('palavratrad', models.CharField(max_length=1000)),
                ('frase', models.CharField(max_length=1000)),
                ('frasetrad', models.CharField(max_length=1000)),
                ('figura1', models.CharField(max_length=1000)),
                ('som1', models.CharField(max_length=1000)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
